[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.28.0"
ci = "github"
installers = ["shell", "powershell", "msi"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
install-path = "CARGO_HOME"
pr-run-mode = "plan"
install-updater = false

[dist.github-custom-runners]
global = "ubuntu-latest"
x86_64-unknown-linux-gnu.runner = "ubuntu-latest"
